# Site settings
title: Strong Paleo
email: contact@strongpaleo.com
description: > # this means to ignore newlines until "baseurl:"
    Sharing our experiences of nutrition and sports to help guide you on your own journey to better health and strength.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://strongpaleo.com" # the base hostname & protocol for your site
twitter_username: strongpaleo

# Build settings
markdown: kramdown
